=== NesterenkoIlya/JavaStudy/Example/src/main/resources/xml/Product.xsd
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema"
            targetNamespace="http://sportshop.com/product"
            elementFormDefault="qualified" xmlns="http://sportshop.com/product">

    <xsd:element name="product" type="Product"/>

    <xsd:complexType name="Product">
        <xsd:sequence>
            <xsd:element name="description" type="xsd:string" />
            <xsd:element name="name" type="xsd:string" />
            <xsd:element name="supply_date" type="xsd:date" />
            <xsd:element name="price" type="xsd:unsignedShort" />
            <xsd:element name="item_weigth" type="xsd:decimal" />
            <xsd:element name="model_year" type="xsd:unsignedShort" />
            <xsd:element name="size" type="xsd:string" />
            <xsd:element name="color" type="xsd:string" />
            <xsd:element name="rating" type="xsd:decimal" />
        </xsd:sequence>
        <xsd:attribute name="id" type="xsd:unsignedByte" use="required" />
    </xsd:complexType>

</xsd:schema>

=== NesterenkoIlya/JavaStudy/target/classes/xml/Product.xml
<?xml version="1.0" encoding="UTF-8"?>
<product xmlns="http://sportshop/product" xsi:schemaLocation="http://sportshop/product Product.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" id="0">
    <description>Sport Costume</description>
    <name>Franklin Sports NCAA</name>
    <supply_date>2022-07-12</supply_date>
    <price>1000</price>
    <item_weigth>0.84</item_weigth>
    <model_year>2010</model_year>
    <size>One Size</size>
    <color>Ohio State Buckeyes</color>
    <rating>5.0</rating>
</product>
