=== NesterenkoIlya/JavaStudy/PW1/src/main/resources/xml/Customer.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema elementFormDefault="qualified"
           xmlns:xsd="http://www.w3.org/2001/XMLSchema"
           targetNamespace="http://eatshop.com/customer" xmlns="http://eatshop.com/customer">

    <xsd:element name="customer" type="Customer"/>

    <xsd:complexType name="Customer">
        <xsd:sequence>
            <xsd:element name="name" type="xsd:string" />
            <xsd:element name="second_name" />
            <xsd:element name="surname" type="xsd:string" />
            <xsd:element name="age" type="xsd:unsignedByte" />
            <xsd:element name="email" type="xsd:string" />
            <xsd:element name="password" type="xsd:string" />
            <xsd:element name="registration_date" type="xsd:date" />
        </xsd:sequence>
        <xsd:attribute name="id" type="xsd:unsignedByte" use="required" />
    </xsd:complexType>


</xsd:schema>

=== NesterenkoIlya/JavaStudy/PW1/src/main/resources/xml/Customer.xml
<?xml version="1.0" encoding="UTF-8"?>
 <tns:customer id="0" xmlns:tns="http://eatshop.com/customer"
           xsd:schemaLocation="http://eatshop.com/customer Customer.xsd"
           xmlns:xsd="http://www.w3.org/2001/XMLSchema-instance">
        <tns:name>Jane</tns:name>
        <tns:second_name></tns:second_name>
        <tns:surname>Bones</tns:surname>
        <tns:age>33</tns:age>
        <tns:email>janebones@gmail.com</tns:email>
        <tns:password>asdas113_qQQ</tns:password>
        <tns:registration_date>2019-09-01</tns:registration_date>
</tns:customer>

=== NesterenkoIlya/JavaStudy/src/main/resources/xml/Customer.xml
<?xml version="1.0" encoding="UTF-8"?>
 <tns:customer id="0" xmlns:tns="http://sportshop/customer"
           xsi:schemaLocation="http://sportshop/customer Customer.xsd"
           xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
        <tns:name>Jane</tns:name>
        <tns:second_name></tns:second_name>
        <tns:surname>Bones</tns:surname>
        <tns:age>33</tns:age>
        <tns:email>janebones@gmail.com</tns:email>
        <tns:password>asdas113_qQQ</tns:password>
        <tns:registration_date>2019-09-01</tns:registration_date>
</tns:customer>
